@startuml "frontend_system"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!include frontend_components.puml
!include frontend_relations.puml

@enduml
