@startuml "frontend_relations"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Rel(customer, frontend, "Browses goods")
Rel(customer, frontend, "Adds items to cart")
Rel(customer, frontend, "Creates a shipping order")
Rel(customer, frontend, "Pays for order")

Rel(frontend, auth_service, "Authenticates users")
Rel(frontend, goods_service, "Gets goods information")
Rel(frontend, goods_service, "Finds goods")
Rel(frontend, cart_service, "Adds/removes items from cart")
Rel(frontend, order_service, "Creates an order from cart")
Rel(frontend, payment_service, "Initiates payment")

@enduml
