@startuml "frontend_components"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container(frontend, "Web UI", "React", "Serves customer", $sprite="react")

@enduml
